# 数据库
spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql://localhost:3306/myweb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis
mybatis:
  type-aliases-package: com.withered.pojo
  mapper-locations: classpath:mapper/*.xml
